import {BookType} from './BookDataprovider'

export const defaultBooks: BookType[] = [
    {
        id: '1',
        name: 'The Great Gatsby',
        content:
            'The story primarily concerns the young and mysterious millionaire Jay Gatsby and his quixotic passion and obsession for the beautiful former debutante Daisy Buchanan.',
        price: 12.99,
        shabak: 'ABC123',
        image: 'great-gatsby.jpg',
        writers: ['F. Scott Fitzgerald'],
        category: '1',
        translators: [],
        publisher: 'Scribner',
        createdAt: new Date('1925-04-10'),
    },
    {
        id: '2',
        name: 'To Kill a Mockingbird',
        content:
            "The story takes place during three years (1933–35) of the Great Depression in the fictional 'tired old town' of Maycomb, Alabama, the seat of Maycomb County.",
        price: 10.99,
        shabak: 'DEF456',
        image: 'to-kill-a-mockingbird.jpg',
        writers: ['Harper Lee'],
        category: '1',
        translators: [],
        publisher: 'J. B. Lippincott & Co.',
        createdAt: new Date('1960-07-11'),
    },
    {
        id: '3',
        name: '1984',
        content:
            '1984 is set in Oceania, which includes the United Kingdom, where the story is set, known as Airstrip One. Winston Smith is a low-ranking member of the ruling Party in London, in the nation of Oceania.',
        price: 14.99,
        shabak: 'GHI789',
        image: '1984.jpg',
        writers: ['George Orwell'],
        category: '1',
        translators: [],
        publisher: 'Secker & Warburg',
        createdAt: new Date('1949-06-08'),
    },
    {
        id: '4',
        name: 'Pride and Prejudice',
        content:
            'Pride and Prejudice is an 1813 romantic novel of manners written by Jane Austen. The novel follows the character development of Elizabeth Bennet, the dynamic protagonist of the book who learns about the repercussions of hasty judgments and comes to appreciate the difference between superficial goodness and actual goodness.',
        price: 11.99,
        shabak: 'JKL012',
        image: 'pride-and-prejudice.jpg',
        writers: ['Jane Austen'],
        category: '1',
        translators: [],
        publisher: 'T. Egerton, Whitehall',
        createdAt: new Date('1813-01-28'),
    },
    {
        id: '5',
        name: 'The Catcher in the Rye',
        content:
            "The novel's plot is simple, detailing 16-year-old Holden Caulfield's experiences in New York City following his expulsion and departure from Pencey Prep, a college preparatory school.",
        price: 9.99,
        shabak: 'MNO345',
        image: 'catcher-in-the-rye.jpg',
        writers: ['J.D. Salinger'],
        category: '1',
        translators: [],
        publisher: 'Little, Brown and Company',
        createdAt: new Date('1951-07-16'),
    },
    {
        id: '6',
        name: 'The Hobbit',
        content:
            "The Hobbit is set in 'Middle-earth', a fantasy world created by Tolkien. The story begins in the Shire, where the hobbit Frodo Baggins acquires the Ring from Bilbo Baggins, his cousin and guardian.",
        price: 13.99,
        shabak: 'PQR678',
        image: 'the-hobbit.jpg',
        writers: ['J.R.R. Tolkien'],
        category: '1',
        translators: [],
        publisher: 'George Allen & Unwin',
        createdAt: new Date('1937-09-21'),
    },
    {
        id: '7',
        name: "Harry Potter and the Philosopher's Stone",
        content:
            'Harry Potter is a series of fantasy novels written by British author J. K. Rowling. The novels chronicle the lives of a young wizard, Harry Potter, and his friends Hermione Granger and Ron Weasley, all of whom are students at Hogwarts School of Witchcraft and Wizardry.',
        price: 15.99,
        shabak: 'STU901',
        image: 'harry-potter-and-the-philosophers-stone.jpg',
        writers: ['J.K. Rowling'],
        category: '1',
        translators: [],
        publisher: 'Bloomsbury',
        createdAt: new Date('1997-06-26'),
    },
    {
        id: '8',
        name: 'Moby-Dick',
        content:
            'The novel was first published as The Whale in London in 1851, and early reviews of Moby-Dick were mixed, ranging from a complete failure to some praise.',
        price: 16.99,
        shabak: 'VWX123',
        image: 'moby-dick.jpg',
        writers: ['Herman Melville'],
        category: '1',
        translators: [],
        publisher: 'Richard Bentley (UK), Harper & Brothers (US)',
        createdAt: new Date('1851-10-18'),
    },
    {
        id: '9',
        name: 'The Lord of the Rings',
        content:
            "The Lord of the Rings is an epic high-fantasy novel written by English author and scholar J. R. R. Tolkien. The story began as a sequel to Tolkien's 1937 fantasy novel The Hobbit, but eventually developed into a much larger work.",
        price: 20.99,
        shabak: 'YZA456',
        image: 'the-lord-of-the-rings.jpg',
        writers: ['J.R.R. Tolkien'],
        category: '1',
        translators: [],
        publisher: 'George Allen & Unwin',
        createdAt: new Date('1954-07-29'),
    },
    {
        id: '10',
        name: 'War and Peace',
        content:
            "War and Peace is a novel by the Russian author Leo Tolstoy, first published serially, then published in its entirety in 1869. It is regarded as one of Tolstoy's finest literary achievements and remains a classic of world literature.",
        price: 18.99,
        shabak: 'BCD789',
        image: 'war-and-peace.jpg',
        writers: ['Leo Tolstoy'],
        category: '1',
        translators: [],
        publisher: 'The Russian Messenger',
        createdAt: new Date('1869-01-01'),
    },
]
